/**
 * The bundled Roxen index: Roxen's vocabulary without a Roxen installation.
 *
 * Generated by `scripts/build-roxen-index.ts` from a pinned Roxen 6.1 revision
 * and committed as `server/src/data/roxen-index.json`. It exists because the
 * failure this change fixes — a Roxen file arriving red — must be fixed for
 * everyone, including a developer reading Roxen code on a machine that has
 * never run Roxen.
 *
 * Two rules govern how it is consulted, and both are about not lying:
 *
 *   - It is a FALLBACK. A detected installation resolves first, so a user sees
 *     their own Roxen's constants rather than the pinned ones. Callers must
 *     reach the index only after ordinary resolution has come up empty.
 *   - It carries no locations. An index entry knows what a symbol is, not
 *     where the user's copy of it lives, so go-to-definition returns nothing
 *     rather than a path into a tree that may not exist. Hover still works.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface RoxenConstantEntry {
  /** Rendered declaration, e.g. `#define TYPE_STRING 1`. */
  signature: string;
  /** The header it comes from, e.g. `module.h`. */
  header: string;
  /** Documentation as markdown; empty when the declaration carried none. */
  markdown: string;
}

export interface RoxenSymbolEntry {
  signature: string;
  markdown: string;
}

export interface RoxenIndexData {
  roxenRevision: string;
  roxenVersion: string;
  /** Flat preprocessor/constant vocabulary, keyed by bare name. */
  constants: Record<string, RoxenConstantEntry>;
  /**
   * Dotted API surface, keyed by FQN.
   *
   * `Roxen.`, `RXML.` and `RoxenModule.` are namespaces Roxen names itself.
   * `predef.` is the fourth, and it is not a Roxen namespace at all: it holds
   * the globals roxenloader injects into Pike's predefined namespace, which a
   * Roxen file reaches bare or writes out as `predef::report_fatal`.
   * `roxen.` and `roxenloader.` are the members of the two of those globals
   * that are bound to a whole source file, and they are lower-case because
   * that is how the reference is written — `roxen.store`.
   */
  symbols: Record<string, RoxenSymbolEntry>;
}

/**
 * Prefix under which roxenloader's injected globals are indexed.
 *
 * They are not members of anything — `report_fatal` is written bare — so this
 * prefix exists only to keep one flat namespace per origin inside `symbols`.
 */
export const ROXEN_GLOBAL_PREFIX = "predef.";

/** Prefix for the module prototype's members, which a module writes bare. */
export const ROXEN_MODULE_PREFIX = "RoxenModule.";

/** An index with nothing in it, for when the data file is unreadable. */
export const EMPTY_ROXEN_INDEX: RoxenIndexData = {
  roxenRevision: "",
  roxenVersion: "",
  constants: {},
  symbols: {},
};

/**
 * Headers the bundled index covers.
 *
 * An `#include` of one of these must not be reported as unresolvable when no
 * installation is present: the symbols it would have defined are known anyway,
 * so the file is not actually missing anything, and a diagnostic would turn a
 * valid file red for no gain.
 */
export function indexCoversHeader(index: RoxenIndexData, header: string): boolean {
  const bare = header.replace(/^[<"]|[>"]$/g, "");
  for (const entry of Object.values(index.constants)) {
    if (entry.header === bare) return true;
  }
  return false;
}

// ---------------------------------------------------------------------------
// Lookup
// ---------------------------------------------------------------------------

/**
 * Look a bare name up in the constant vocabulary.
 *
 * Returns null for anything unknown, including when Roxen mode is off — the
 * caller is responsible for not asking in that case, but a null here keeps a
 * missed gate from leaking Roxen symbols into a plain Pike file.
 */
export function lookupRoxenConstant(
  index: RoxenIndexData,
  name: string,
): RoxenConstantEntry | null {
  return index.constants[name] ?? null;
}

/** Look a dotted name up in the API surface. */
export function lookupRoxenSymbol(
  index: RoxenIndexData,
  fqn: string,
): RoxenSymbolEntry | null {
  return index.symbols[fqn] ?? null;
}

/**
 * Resolve a bare identifier against the API surface as well as the constants.
 *
 * Roxen module code refers to prototype members (`find_file`, `defvar`,
 * `query_location`) by bare name, because it inherits the prototype. The index
 * stores those under `RoxenModule.`, so a bare lookup tries that prefix.
 *
 * `report_fatal` and its neighbours are written bare for a different reason:
 * roxenloader has added them to Pike's own namespace, so they resolve like a
 * builtin. Those are under `predef.`, and are tried second — a module's
 * prototype member shadows a global of the same name, exactly as in Pike.
 */
export function lookupRoxenIdentifier(
  index: RoxenIndexData,
  name: string,
): { signature: string; markdown: string; header?: string } | null {
  const constant = lookupRoxenConstant(index, name);
  if (constant) return constant;

  const member = lookupRoxenSymbol(index, `${ROXEN_MODULE_PREFIX}${name}`);
  if (member) return member;

  return lookupRoxenSymbol(index, `${ROXEN_GLOBAL_PREFIX}${name}`);
}

// ---------------------------------------------------------------------------
// Completion
// ---------------------------------------------------------------------------

/** One completion candidate from the index, in a form the caller can shape. */
export interface RoxenCompletionCandidate {
  name: string;
  detail: string;
  documentation: string;
  /** True for `#define`/`constant` names, false for API members. */
  isConstant: boolean;
}

/**
 * Every name the index can offer for completion in a Roxen file.
 *
 * Only bare names: the dotted API surface is offered through member completion
 * on `Roxen.`/`RXML.`, not as thousands of top-level entries. `RoxenModule.`
 * members are offered bare because inheriting the prototype is what makes them
 * available without a prefix, and `predef.` globals because roxenloader has
 * put them in Pike's own namespace, where nothing needs a prefix either.
 */
export function roxenCompletionCandidates(index: RoxenIndexData): RoxenCompletionCandidate[] {
  const candidates: RoxenCompletionCandidate[] = [];

  for (const [name, entry] of Object.entries(index.constants)) {
    candidates.push({
      name,
      detail: entry.signature,
      documentation: entry.markdown,
      isConstant: true,
    });
  }

  const seen = new Set<string>();
  for (const prefix of [ROXEN_MODULE_PREFIX, ROXEN_GLOBAL_PREFIX]) {
    for (const [fqn, entry] of Object.entries(index.symbols)) {
      if (!fqn.startsWith(prefix)) continue;
      const name = fqn.slice(prefix.length);
      // Nested members (RoxenModule.Foo.bar) are not in bare scope.
      if (name.includes(".") || seen.has(name)) continue;
      seen.add(name);
      candidates.push({
        name,
        detail: entry.signature,
        documentation: entry.markdown,
        isConstant: false,
      });
    }
  }

  return candidates;
}

/**
 * The globals roxenloader injects, for `predef::` scope completion.
 *
 * Pike's own predefined names come from the builtin index; these are what a
 * Roxen file additionally finds there, and asking for them separately keeps
 * the caller from having to know the prefix.
 */
export function roxenInjectedGlobals(index: RoxenIndexData): RoxenCompletionCandidate[] {
  return roxenMembersOf(index, ROXEN_GLOBAL_PREFIX.slice(0, -1));
}

/**
 * Members offered after a dotted Roxen prefix, e.g. `Roxen.` or `RXML.`.
 *
 * Returns the immediate children of `prefix` only — `RXML.` offers `Tag`, not
 * `Tag.eval`.
 */
export function roxenMembersOf(index: RoxenIndexData, prefix: string): RoxenCompletionCandidate[] {
  const dotted = `${prefix}.`;
  const seen = new Set<string>();
  const members: RoxenCompletionCandidate[] = [];

  for (const [fqn, entry] of Object.entries(index.symbols)) {
    if (!fqn.startsWith(dotted)) continue;
    const rest = fqn.slice(dotted.length);
    if (rest.includes(".")) continue;
    if (seen.has(rest)) continue;
    seen.add(rest);
    members.push({
      name: rest,
      detail: entry.signature,
      documentation: entry.markdown,
      isConstant: false,
    });
  }

  return members;
}

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

/**
 * Narrow parsed JSON to a `RoxenIndexData`, or return the empty index.
 *
 * Static data is loaded at startup and a malformed file must degrade to "no
 * Roxen symbols", never crash the server before it has accepted a connection.
 */
export function asRoxenIndex(value: unknown): RoxenIndexData {
  if (typeof value !== "object" || value === null) return EMPTY_ROXEN_INDEX;
  const obj = value as Record<string, unknown>;
  const constants = obj["constants"];
  const symbols = obj["symbols"];
  if (typeof constants !== "object" || constants === null) return EMPTY_ROXEN_INDEX;
  if (typeof symbols !== "object" || symbols === null) return EMPTY_ROXEN_INDEX;
  return {
    roxenRevision: typeof obj["roxenRevision"] === "string" ? obj["roxenRevision"] : "",
    roxenVersion: typeof obj["roxenVersion"] === "string" ? obj["roxenVersion"] : "",
    constants: constants as Record<string, RoxenConstantEntry>,
    symbols: symbols as Record<string, RoxenSymbolEntry>,
  };
}
